# Generated by Django 5.0.4 on 2024-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='default wallet', max_length=100),
        ),
    ]
