# Generated by Django 5.0.4 on 2024-04-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_remove_transaction_description_transaction_userinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='userinfo',
            new_name='user',
        ),
    ]
